# Generated by Django 5.1.2 on 2024-10-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
    ]
