# Generated by Django 5.1.2 on 2024-10-30 14:07

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20241030_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercodes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 30, 14, 3, 1, 465930, tzinfo=datetime.timezone.utc), verbose_name='تاریخ بارگذاری اسکرین شات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordercodes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به روزرسانی'),
        ),
        migrations.AddField(
            model_name='requestcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاریخ بارگذاری اسکرین شات'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestcustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین به روزرسانی'),
        ),
    ]
